### ISSUE TITLE
Improvements to the requests file

### ISSUE THREAD

**Issue by petlyh** [Arcticons-Team/Arcticons#1831]
(Continuation of the discussion in the comments of #1822)

Some possible improvements to the requests file:
- Move to a machine readable format to make it easier for scripts to interact with it. My suggestion would be YAML since it has a good tradeoff between human and machine readability. Example of a possible structure:
```yaml
requests:
  - name: OnStream
    appfilter: <item component="ComponentInfo{com.maertsno.m/com.maertsno.m.ui.main.MainActivity}" drawable="onstream"/>
    links:
      - https://play.google.com/store/apps/details?id=com.maertsno.m
      - https://f-droid.org/en/packages/com.maertsno.m/
    request_count: 14
    last_request_time: 1700051822
```
- Only include app store links that actually work. This would likely involve a script that looks up the app IDs of new requests in multiple app stores to see if they have the requested app. I have already written code previously that can be used for this (currently checks F-Droid, IzzyOnDroid and Google Play) and I would be willing to write the script for this if desired.
- ~~Remove "Last requested time" to reduce file size if it's not going to be used for anything.~~
I didn't realize it was being used to filter old requests. My bad.
