### ISSUE TITLE
Automatic Google Play publishing with a new release

### ISSUE THREAD

**Issue by Donnnno** [Arcticons-Team/Arcticons#2369]
Gonna ask the Delta devs for help with this :)

**Comment by Donnnno** [comment]
https://github.com/r0adkll/upload-google-play

```yaml
    - name: Upload AAB to Google Play beta channel
      uses: r0adkll/upload-google-play@v1
      with:
        track: beta
        status: completed
        releaseFiles: ${{ env.filename }}.aab
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT }}
        packageName: ${{ env.package_name }}
        mappingFile: app/build/outputs/mapping/playRelease/mapping.txt
        whatsNewDirectory: changelog
        inAppUpdatePriority: 5
      if: |
        github.repository_owner == env.organization &&
        inputs.publish == true

    - name: Promote beta to production channel
      uses: kevin-david/promote-play-release@v1.1.0
      with:
        service-account-json-raw: ${{ secrets.SERVICE_ACCOUNT }}
        package-name: ${{ env.package_name }}
        inapp-update-priority: 5
        user-fraction: 1.0
      if: |
        github.repository_owner == env.organization &&
        inputs.release_type == 'prod' &&
        inputs.publish == true
```
